apiVersion: apps/v1
kind: Deployment
metadata:
   name: auth
spec:
   replicas: 2
   selector:
      matchLabels:
         components: auth
   template:
      metadata:
         labels:
            components: auth
      spec:
         containers:
            - name: auth
              image: anpol84/oauth:0.0.2
              ports:
                 - containerPort: 8080
              env:
                 - name: POSTGRES_URL
                   value: jdbc:postgresql://db:5432/auth?schema=public&user=user&password=password
