apiVersion: apps/v1
kind: Deployment
metadata:
   name: db
spec:
   replicas: 1
   selector:
      matchLabels:
         components: db
   template:
      metadata:
         labels:
            components: db
      spec:
         containers:
            - name: db
              image: postgres:16.0
              ports:
                 - containerPort: 5432
              env:
                 - name: POSTGRES_DB
                   value: notes
                 - name: POSTGRES_USER
                   valueFrom:
                     secretKeyRef:
                       name: db-cred
                       key: POSTGRES_USER
                 - name: POSTGRES_PASSWORD
                   valueFrom:
                     secretKeyRef:
                       name: db-cred
                       key: POSTGRES_PASSWORD
              volumeMounts:
                 - name: db-data
                   mountPath: /var/lib/postgresql/data
         volumes:
            - name: db-data
              persistentVolumeClaim:
                 claimName: db
