apiVersion: apps/v1
kind: Deployment
metadata:
   name: logger
spec:
   replicas: 2
   selector:
      matchLabels:
         components: logger
   template:
      metadata:
         labels:
            components: logger
      spec:
         containers:
            - name: logger
              image: anpol84/logger:0.0.1
              ports:
                 - containerPort: 8083
              env:
                 - name: POSTGRES_URL
                   value: jdbc:postgresql://db:5432/logger?schema=public&user=user&password=password
                 - name: VALIDATOR_URL
                   value: http://172.27.167.91
